language: node_js

cache:
  directories:
    - "node_modules"

git:
  depth: 5

before_install:
  - npm i -g npm@latest

install:
  - npm ci
  - npm run build

jobs:
  include:
    - stage: "Test"
      name: "Lint"
      script: npm run lint
      node_js: 12
