language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "12"

cache:
  directories:
    - "node_modules"

git:
  depth: 5

branches:
  only: master

before_install:
  - npm i -g npm@latest

install:
  - npm ci
  - npm run build

script:
  - npm run lint
